package io.github.loskovdm.designsystem.theme

import androidx.compose.ui.graphics.Color

// Light — neutral surfaces, blue primary
val primaryLight = Color(0xFF1565C0)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD1E4FF)
val onPrimaryContainerLight = Color(0xFF001D36)
val secondaryLight = Color(0xFF535F70)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD7E3F7)
val onSecondaryContainerLight = Color(0xFF101C2B)
val tertiaryLight = Color(0xFF6B5778)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF2DAFF)
val onTertiaryContainerLight = Color(0xFF251431)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8F9FA)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFE3E5E8)
val onSurfaceVariantLight = Color(0xFF44474A)
val outlineLight = Color(0xFF74777A)
val outlineVariantLight = Color(0xFFC4C7CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3033)
val inverseOnSurfaceLight = Color(0xFFF1F0F4)
val inversePrimaryLight = Color(0xFF90CAF9)
val surfaceDimLight = Color(0xFFD9DADC)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F4F6)
val surfaceContainerLight = Color(0xFFEDEEF0)
val surfaceContainerHighLight = Color(0xFFE7E8EA)
val surfaceContainerHighestLight = Color(0xFFE1E2E4)

// Dark — neutral surfaces, light blue primary
val primaryDark = Color(0xFF90CAF9)
val onPrimaryDark = Color(0xFF003258)
val primaryContainerDark = Color(0xFF004A77)
val onPrimaryContainerDark = Color(0xFFD1E4FF)
val secondaryDark = Color(0xFFBBC7DB)
val onSecondaryDark = Color(0xFF253140)
val secondaryContainerDark = Color(0xFF3B4858)
val onSecondaryContainerDark = Color(0xFFD7E3F7)
val tertiaryDark = Color(0xFFD6BEE4)
val onTertiaryDark = Color(0xFF3B2948)
val tertiaryContainerDark = Color(0xFF523F5F)
val onTertiaryContainerDark = Color(0xFFF2DAFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFE2E2E5)
val surfaceDark = Color(0xFF1E1E1E)
val onSurfaceDark = Color(0xFFE2E2E5)
val surfaceVariantDark = Color(0xFF44474A)
val onSurfaceVariantDark = Color(0xFFC4C7CA)
val outlineDark = Color(0xFF8E9194)
val outlineVariantDark = Color(0xFF44474A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E5)
val inverseOnSurfaceDark = Color(0xFF2F3033)
val inversePrimaryDark = Color(0xFF1565C0)
val surfaceDimDark = Color(0xFF121212)
val surfaceBrightDark = Color(0xFF38393C)
val surfaceContainerLowestDark = Color(0xFF0D0D0D)
val surfaceContainerLowDark = Color(0xFF1A1A1A)
val surfaceContainerDark = Color(0xFF1E1E1E)
val surfaceContainerHighDark = Color(0xFF282828)
val surfaceContainerHighestDark = Color(0xFF333333)
